### ISSUE TITLE
Error with scrape_event.py

### ISSUE THREAD

**Issue by eschibli** [shortlikeafox/tiger-millionaire#25]
Hello devs,

Thank you for starting this exciting project! 

When trying to scrape events by running `scrape_event.py`, I receive the following error, regardless to the target event URL: 

```
  df = pd.concat([df, df_temp])
['', '', 'Shana Dobson', 'Welterweight', '', '', 'Jordan Wright', 'Welterweight', '']
Traceback (most recent call last):
  File "scrape_event.py", line 167, in <module>
    df['weight_class']=weight_class_list
  File "C:\Users\erics\Anaconda3\lib\site-packages\pandas\core\frame.py", line 3370, in __setitem__
    self._set_item(key, value)
  File "C:\Users\erics\Anaconda3\lib\site-packages\pandas\core\frame.py", line 3445, in _set_item
    value = self._sanitize_column(key, value)
  File "C:\Users\erics\Anaconda3\lib\site-packages\pandas\core\frame.py", line 3630, in _sanitize_column
    value = sanitize_index(value, self.index, copy=False)
  File "C:\Users\erics\Anaconda3\lib\site-packages\pandas\core\internals\construction.py", line 519, in sanitize_index
    raise ValueError('Length of values does not match length of index')
ValueError: Length of values does not match length of index
```

Do you have any suggestions? If `scrape_event.py` requires further customization to use, could you provide a quick guide if possible? Thanks either way!

**Comment by shortlikeafox** [comment]
Yes!

They changed ufcstats.com and broke that scraper. But don't fret! The
scraper that used to only work for completed events should work for all
events.

Try scrape_completed_event.py (I think that's what it's called). It should
work.

Let me know if you have any issues.


Thanks for your interest!
-Matt

**Comment by eschibli** [comment]
Thanks, that indeed works.

**Comment by shortlikeafox** [comment]
Purge removed this file
